Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 
Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
ёЗатем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

In [2]:
a = np.array([[ 1. , 6.],
             [ 2. , 8.],
             [ 3. , 11.],
             [ 3., 10.],
             [1. , 7.]], dtype=float)

In [3]:
mean_a = a.mean(axis=0)

In [8]:
print(mean_a)

[2.  8.4]


Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив 
должен иметь размер 5x2.

Так наверное грамотнее 

In [4]:
a_centered = a + (mean_a * -1)

In [11]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]



Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться 
величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [5]:
A = a_centered[0:5, 0].copy()
print(A)

[-1.  0.  1.  1. -1.]


In [7]:
B = a_centered[0:5, 1].copy()
print(B)

[-2.4 -0.4  2.6  1.6 -1.4]


In [8]:
a_centered_sp = A.dot(B)
print(a_centered_sp)

8.0


In [9]:
N = a.shape
print(N[0])

5


In [10]:
a_centered_sp_k = a_centered_sp * (1 / (N[0] - 1))

In [23]:
print(a_centered_sp_k)

2.0
